stages:
  - install
  - publish

cache:
  untracked: true
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install:
  stage: install
  tags:
    - shared
  only:
    - master
  script:
    - tyn

publish:
  stage: publish
  tags:
    - shared
  only:
    - master
  cache:
    policy: pull
  script:
    - bash ./deploy.sh
